package com.team6.dao;

import com.team6.entity.Comment;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    Comment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Comment record);

   List<Map<String,Object>> queryCommentByGoodsId(@Param("goodsId") int goodsId,@Param("num")int num);

   //查询评论总数
   int queryCommentCountByGoodsId(@Param("goodsId") int goodsId);

   Map<String ,Object> quertReplyById(@Param("id") int id);

    /**
     * 查询用户以评论的商品
     * @param userId
     * @return
     */
   List<Map> queryCommentByUserId(@Param("userId") int userId);

    /**
     * 查询用户没有评论的商品
     * @param userId
     * @return
     */
   List<Map> queryNoCommentByUserId(@Param("userId") int userId);

    /**
     * 查询商家商品的评论
     * @param shopId
     * @return
     */
   List queryShopCommentByShopId(@Param("shopId") int shopId);
}