package com.team6.dao;

import com.team6.dto.order.UserOrderData;
import com.team6.entity.OrderDetails;

import java.util.List;

public interface OrderDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbggenerated
     */
    int insert(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbggenerated
     */
    int insertSelective(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbggenerated
     */
    OrderDetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderDetails record);

    /**
     * 删除相关订单的详细信息
     * @param order_id
     * @return
     */
    int deleterByOrderId(Integer order_id);

    /**
     * 封装订单的详细信息
     */
    List<UserOrderData> queryOrderDate(Integer order_id);
}