package com.team6.dao;

import com.team6.entity.ShoppingCar;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ShoppingCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated
     */
    int insert(ShoppingCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated
     */
    int insertSelective(ShoppingCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated
     */
    ShoppingCar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShoppingCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShoppingCar record);

    public ShoppingCar queryByUserIdAndGoodsId(@Param("goodsId")int goodsId,@Param("userId")int userId);

    public List queryGidCountByUserid(Integer userid);

    public int delUserGoodsById(@Param("goodsId") int goodsId,@Param("userId") int userId);
}