package com.team6.dao;

import com.team6.entity.ShoppingCar;

public interface ShoppingCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated
     */
    int insert(ShoppingCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated
     */
    int insertSelective(ShoppingCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated
     */
    ShoppingCar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShoppingCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShoppingCar record);
}