package com.team6.entity;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.entity_id
     *
     * @mbggenerated
     */
    private Integer entityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.entity_type
     *
     * @mbggenerated
     */
    private Integer entityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.description_score
     *
     * @mbggenerated
     */
    private Integer descriptionScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.service_score
     *
     * @mbggenerated
     */
    private Integer serviceScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.logistics_score
     *
     * @mbggenerated
     */
    private Integer logisticsScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_id
     *
     * @return the value of comment.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_id
     *
     * @param userId the value for comment.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.entity_id
     *
     * @return the value of comment.entity_id
     *
     * @mbggenerated
     */
    public Integer getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.entity_id
     *
     * @param entityId the value for comment.entity_id
     *
     * @mbggenerated
     */
    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.entity_type
     *
     * @return the value of comment.entity_type
     *
     * @mbggenerated
     */
    public Integer getEntityType() {
        return entityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.entity_type
     *
     * @param entityType the value for comment.entity_type
     *
     * @mbggenerated
     */
    public void setEntityType(Integer entityType) {
        this.entityType = entityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.description_score
     *
     * @return the value of comment.description_score
     *
     * @mbggenerated
     */
    public Integer getDescriptionScore() {
        return descriptionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.description_score
     *
     * @param descriptionScore the value for comment.description_score
     *
     * @mbggenerated
     */
    public void setDescriptionScore(Integer descriptionScore) {
        this.descriptionScore = descriptionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.service_score
     *
     * @return the value of comment.service_score
     *
     * @mbggenerated
     */
    public Integer getServiceScore() {
        return serviceScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.service_score
     *
     * @param serviceScore the value for comment.service_score
     *
     * @mbggenerated
     */
    public void setServiceScore(Integer serviceScore) {
        this.serviceScore = serviceScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.logistics_score
     *
     * @return the value of comment.logistics_score
     *
     * @mbggenerated
     */
    public Integer getLogisticsScore() {
        return logisticsScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.logistics_score
     *
     * @param logisticsScore the value for comment.logistics_score
     *
     * @mbggenerated
     */
    public void setLogisticsScore(Integer logisticsScore) {
        this.logisticsScore = logisticsScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}